# Permalinks
permalink:           pretty

# Setup
title:               Stephen J. Kaplan
tagline:             Data Science, Machine Learning, and other things.
url:                 http://stephenjkaplan.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Stephen Kaplan
  email:             stevejkaplan@gmail.com

# Custom vars
version:             0.0.0
github:
  repo:              https://github.com/stephenjkaplan

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Résumé: '/resume'
  Archive: '/archive'
  Feed: '/index.html'

